owner:
  name: CCY
  avatar: ccy21.jpg
  email: cuicy21@mails.tsinghua.edu.cn
  github: ccy23thu

url: https://ccy23thu.github.io
markdown: kramdown
permalink: /blog/:year/:month/:day/:title

# Links to include in top navigation
# For external links add external: true
links:
  - title: About Me
    url: /
    sublinks:
      - title: sub 1
        url: /sub_1/
      - title: sub 2
        url: /sub_2/
  - title: Publications
    url: /publications/
  - title: Awards
    url: /awards/
  - title: Blog
    url: /blog/
    sublinks:
      - title: Auto.
        url: /auto/
      - title: Daily
        url: /daily/
      - title: ACGN
        url: /acgn/
  - title: Tools
    url: /tools/
